// Curated collection of iconic IPL moments for the What-If Engine
// over/ball are 0-indexed to match backend data format
// innings: which innings to target (2 = chase, 1 = first innings)

const ICONIC_MOMENTS = [
  {
    id: "2019_60",
    innings: 2,
    over: 19,
    ball: 5,
    title: "MI vs CSK — 2019 Final",
    subtitle: "The Last Ball Thriller",
    desc: "What if Shardul Thakur hit the winning boundary off Malinga's last ball instead of being bowled?",
    color: "#004BA0",
    gradient: "from-[#004BA0] to-[#00396b]",
    emoji: "🏆",
    year: "2019",
    venue: "Hyderabad",
    tag: "FINAL"
  },
  {
    id: "2023_74",
    innings: 2,
    over: 14,
    ball: 5,
    title: "GT vs CSK — 2023 Final",
    subtitle: "Dhoni's Last Dance",
    desc: "What if Mohit Sharma bowled a perfect yorker to Jadeja when CSK needed 10 off the last 2 balls?",
    color: "#F9CD05",
    gradient: "from-[#F9CD05] to-[#c9a004]",
    emoji: "⭐",
    year: "2023",
    venue: "Ahmedabad",
    tag: "FINAL"
  },
  {
    id: "2017_59",
    innings: 2,
    over: 18,
    ball: 6,
    title: "MI vs RPS — 2017 Final",
    subtitle: "Smith's Last Stand",
    desc: "What if Steve Smith survived the 19th over and took Pune to the target against Johnson?",
    color: "#9C27B0",
    gradient: "from-[#9C27B0] to-[#7B1FA2]",
    emoji: "🔥",
    year: "2017",
    venue: "Hyderabad",
    tag: "FINAL"
  },
  {
    id: "2016_60",
    innings: 2,
    over: 13,
    ball: 2,
    title: "RCB vs SRH — 2016 Final",
    subtitle: "Kohli's Heartbreak",
    desc: "What if Virat Kohli was not out on this ball and continued his masterclass to chase down 209?",
    color: "#D4213D",
    gradient: "from-[#D4213D] to-[#a51a30]",
    emoji: "💔",
    year: "2016",
    venue: "Bangalore",
    tag: "FINAL"
  },
  {
    id: "2008_58",
    innings: 2,
    over: 17,
    ball: 3,
    title: "CSK vs RR — 2008 Final",
    subtitle: "Warne's Underdogs",
    desc: "What if Yusuf Pathan was dismissed before his explosive cameo that sealed the first-ever IPL title?",
    color: "#EB1B99",
    gradient: "from-[#EB1B99] to-[#c01580]",
    emoji: "👑",
    year: "2008",
    venue: "Mumbai",
    tag: "FINAL"
  },
  {
    id: "2014_60",
    innings: 2,
    over: 15,
    ball: 3,
    title: "KKR vs KXIP — 2014 Final",
    subtitle: "Pandey's Match-Winner",
    desc: "What if Manish Pandey was caught at long-on when KKR still needed 50 off 28 balls?",
    color: "#3A225D",
    gradient: "from-[#3A225D] to-[#2a1845]",
    emoji: "⚡",
    year: "2014",
    venue: "Bangalore",
    tag: "FINAL"
  },
  {
    id: "2024_36",
    innings: 2,
    over: 18,
    ball: 4,
    title: "KKR vs RCB — 2024",
    subtitle: "Salt's Runout Drama",
    desc: "What if Phil Salt survived the crucial runout and continued his assault on the RCB bowling attack?",
    color: "#3A225D",
    gradient: "from-[#3A225D] to-[#2a1845]",
    emoji: "🏏",
    year: "2024",
    venue: "Kolkata",
    tag: "THRILLER"
  },
  {
    id: "2024_33",
    innings: 2,
    over: 19,
    ball: 4,
    title: "MI vs PBKS — 2024",
    subtitle: "Ashutosh's Miracle",
    desc: "What if Ashutosh Sharma survived one more ball and completed the greatest chase in IPL history?",
    color: "#D71920",
    gradient: "from-[#D71920] to-[#a51318]",
    emoji: "🌪️",
    year: "2024",
    venue: "Mohali",
    tag: "THRILLER"
  },
  {
    id: "2012_74",
    innings: 2,
    over: 16,
    ball: 3,
    title: "CSK vs KKR — 2012 Final",
    subtitle: "Bisla's Masterclass",
    desc: "What if Gautam Gambhir stayed on to anchor KKR's chase instead of falling for 2 at the top?",
    color: "#3A225D",
    gradient: "from-[#3A225D] to-[#2a1845]",
    emoji: "🎯",
    year: "2012",
    venue: "Chennai",
    tag: "FINAL"
  },
  {
    id: "2009_57",
    innings: 2,
    over: 15,
    ball: 4,
    title: "RCB vs DC — 2009 Final",
    subtitle: "The SA Showdown",
    desc: "What if Gilchrist survived Kumble's spell and took Deccan Chargers to the title in South Africa?",
    color: "#FF822A",
    gradient: "from-[#FF822A] to-[#cc6820]",
    emoji: "🇿🇦",
    year: "2009",
    venue: "Johannesburg",
    tag: "FINAL"
  }
];

export default ICONIC_MOMENTS;
